### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by championshuttler**
cc @Treevuhh @DecentralizedDan 

Treva do we have any email id assigned to report security bugs yet?

### CODE REVIEW

**Comment by Treevuhh** [comment]
In the interlock-whitepaper repo [README.md](https://github.com/interlock-network/interlock-whitepaper#readme) it says, 
>"As for bug reports, please use the [Issues tab](https://github.com/interlock-network/interlock-whitepaper/issues) and create a new issue, whether it's a typo in the white paper or you want something added/removed."

So I'm thinking we should direct whoever to create an issue for any security bug. @DecentralizedDan has taken this question to #team-general in Discord as well.

**Comment by championshuttler** [comment]
> So I'm thinking we should direct whoever to create an issue for any security bug. @DecentralizedDan has taken this question to #team-general in Discord as well.

It will put us in a bad situation as everyone will know about security issue and do something bad out of it, thats why I want to discourage opening public issues for security bugs

**Comment by Treevuhh** [comment]
Yes. I understand, that makes sense. I figured there might be a way to have private issues. Just thinking about keeping things in git as much as possible. Still understanding its abilities though.

**Comment by DecentralizedDan** [comment]
@Treevuhh You're correct that, when it comes to reporting bugs, users can simply create an issue in GitHub.
* but there's generally a specific email for security issues for the reason @championshuttler described -- we don't want our security issues being public knowledge! (until after we fix them at least)

**Pull request merged**
